In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [2]:
df = pd.read_csv('train.csv')
df2 = pd.read_csv('test.csv')

In [3]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [5]:
df.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [6]:
df['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [7]:
df['Sex'] = df['Sex'].replace({'male':1,'female':0})
df['Embarked'] = df['Embarked'].replace({'S':1,'C':2,'Q':3})
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    1  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1   
2                               Heikkinen, Miss. Laina    0  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1   
4                             Allen, Mr. William Henry    1  35.0      0   
..                                                 ...  ...   ...    ...   
886                              Montvila, Rev. Juozas    1  27.0      0   
887                       Graham, Miss. Margaret Edith    0  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"    0   NaN      1   
889                              Behr, Mr. Karl Howell    1  26.0      0   
890                                Dooley, Mr. Patrick    1  32.0      0   

     Parch            Ticket     Fare Cabin  Embarked  
0        0         A/5 21171   7.2500   NaN       1.0  
1        0          PC 17599  71.2833   C85       2.0  
2        0  STON/O2. 3101282   7.9250   NaN       1.0  
3        0            113803  53.1000  C123       1.0  
4        0            373450   8.0500   NaN       1.0  
..     ...               ...      ...   ...       ...  
886      0            211536  13.0000   NaN       1.0  
887      0            112053  30.0000   B42       1.0  
888      2        W./C. 6607  23.4500   NaN       1.0  
889      0            111369  30.0000  C148       2.0  
890      0            370376   7.7500   NaN       3.0  

[891 rows x 12 columns]

In [8]:
df2['Sex'] = df2['Sex'].replace({'male':1,'female':0})
df2['Embarked'] = df2['Embarked'].replace({'S':1,'C':2,'Q':3})
df2

PassengerId  Pclass                                          Name  Sex  \
0            892       3                              Kelly, Mr. James    1   
1            893       3              Wilkes, Mrs. James (Ellen Needs)    0   
2            894       2                     Myles, Mr. Thomas Francis    1   
3            895       3                              Wirz, Mr. Albert    1   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)    0   
..           ...     ...                                           ...  ...   
413         1305       3                            Spector, Mr. Woolf    1   
414         1306       1                  Oliva y Ocana, Dona. Fermina    0   
415         1307       3                  Saether, Mr. Simon Sivertsen    1   
416         1308       3                           Ware, Mr. Frederick    1   
417         1309       3                      Peter, Master. Michael J    1   

      Age  SibSp  Parch              Ticket      Fare Cabin  Embarked  
0    34.5      0      0              330911    7.8292   NaN         3  
1    47.0      1      0              363272    7.0000   NaN         1  
2    62.0      0      0              240276    9.6875   NaN         3  
3    27.0      0      0              315154    8.6625   NaN         1  
4    22.0      1      1             3101298   12.2875   NaN         1  
..    ...    ...    ...                 ...       ...   ...       ...  
413   NaN      0      0           A.5. 3236    8.0500   NaN         1  
414  39.0      0      0            PC 17758  108.9000  C105         2  
415  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN         1  
416   NaN      0      0              359309    8.0500   NaN         1  
417   NaN      1      1                2668   22.3583   NaN         2  

[418 rows x 11 columns]

In [11]:
df['Age'].median()

28.0

In [12]:
df['Age'] = df['Age'].fillna(28.0)
df2['Age'] = df2['Age'].fillna(28.0)

In [13]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [14]:
df.drop(columns=['Cabin','Name','Ticket'],inplace=True)

In [15]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       2
dtype: int64

In [16]:
df.dropna(inplace=True)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  889 non-null    int64  
 1   Survived     889 non-null    int64  
 2   Pclass       889 non-null    int64  
 3   Sex          889 non-null    int64  
 4   Age          889 non-null    float64
 5   SibSp        889 non-null    int64  
 6   Parch        889 non-null    int64  
 7   Fare         889 non-null    float64
 8   Embarked     889 non-null    float64
dtypes: float64(3), int64(6)
memory usage: 69.5 KB


In [18]:
df['Embarked'] = df['Embarked'].astype('int64')
df2['Embarked'] = df2['Embarked'].astype('int64')

In [19]:
df.describe()

PassengerId    Survived      Pclass         Sex         Age  \
count   889.000000  889.000000  889.000000  889.000000  889.000000   
mean    446.000000    0.382452    2.311586    0.649044   29.315152   
std     256.998173    0.486260    0.834700    0.477538   12.984932   
min       1.000000    0.000000    1.000000    0.000000    0.420000   
25%     224.000000    0.000000    2.000000    0.000000   22.000000   
50%     446.000000    0.000000    3.000000    1.000000   28.000000   
75%     668.000000    1.000000    3.000000    1.000000   35.000000   
max     891.000000    1.000000    3.000000    1.000000   80.000000   

            SibSp       Parch        Fare    Embarked  
count  889.000000  889.000000  889.000000  889.000000  
mean     0.524184    0.382452   32.096681    1.362205  
std      1.103705    0.806761   49.697504    0.636157  
min      0.000000    0.000000    0.000000    1.000000  
25%      0.000000    0.000000    7.895800    1.000000  
50%      0.000000    0.000000   14.454200    1.000000  
75%      1.000000    0.000000   31.000000    2.000000  
max      8.000000    6.000000  512.329200    3.000000

In [20]:
df['Survived_'] = df['Survived'].astype('Bool')
df['Pclass_'] = df['Pclass'].astype('category')
df['Sex_'] = df['Sex'].astype('category')
df['Embarked_'] = df['Embarked'].astype('category')

In [29]:
df2['Pclass_'] = df2['Pclass'].astype('category')
df2['Sex_'] = df2['Sex'].astype('category')
df2['Embarked_'] = df2['Embarked'].astype('category')

In [21]:
df.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked  \
0            1         0       3    1  22.0      1      0   7.2500         1   
1            2         1       1    0  38.0      1      0  71.2833         2   
2            3         1       3    0  26.0      0      0   7.9250         1   
3            4         1       1    0  35.0      1      0  53.1000         1   
4            5         0       3    1  35.0      0      0   8.0500         1   

   Survived_ Pclass_ Sex_ Embarked_  
0      False       3    1         1  
1       True       1    0         2  
2       True       3    0         1  
3       True       1    0         1  
4      False       3    1         1

In [24]:
Age_group = [0,22,28,35,50,100]
Age_label = [1,2,3,4,5]
df['Age_'] = pd.cut(df['Age'],bins=Age_group,labels=Age_label)
df.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked  \
0            1         0       3    1  22.0      1      0   7.2500         1   
1            2         1       1    0  38.0      1      0  71.2833         2   
2            3         1       3    0  26.0      0      0   7.9250         1   
3            4         1       1    0  35.0      1      0  53.1000         1   
4            5         0       3    1  35.0      0      0   8.0500         1   

   Survived_ Pclass_ Sex_ Embarked_ Age_  
0      False       3    1         1    1  
1       True       1    0         2    4  
2       True       3    0         1    2  
3       True       1    0         1    3  
4      False       3    1         1    3

In [31]:
Age_group = [0,22,28,35,50,100]
Age_label = [1,2,3,4,5]
df2['Age_'] = pd.cut(df['Age'],bins=Age_group,labels=Age_label)
df2.head()

PassengerId  Pclass                                          Name  Sex  \
0          892       3                              Kelly, Mr. James    1   
1          893       3              Wilkes, Mrs. James (Ellen Needs)    0   
2          894       2                     Myles, Mr. Thomas Francis    1   
3          895       3                              Wirz, Mr. Albert    1   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)    0   

    Age  SibSp  Parch   Ticket     Fare Cabin  Embarked Pclass_ Sex_  \
0  34.5      0      0   330911   7.8292   NaN         3       3    1   
1  47.0      1      0   363272   7.0000   NaN         1       3    0   
2  62.0      0      0   240276   9.6875   NaN         3       2    1   
3  27.0      0      0   315154   8.6625   NaN         1       3    1   
4  22.0      1      1  3101298  12.2875   NaN         1       3    0   

  Embarked_ Age_  
0         3    1  
1         1    4  
2         3    2  
3         1    3  
4         1    3

In [32]:
df2.drop(columns=['Cabin','Name','Ticket'],inplace=True)

In [33]:
df2.head()

PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked Pclass_  \
0          892       3    1  34.5      0      0   7.8292         3       3   
1          893       3    0  47.0      1      0   7.0000         1       3   
2          894       2    1  62.0      0      0   9.6875         3       2   
3          895       3    1  27.0      0      0   8.6625         1       3   
4          896       3    0  22.0      1      1  12.2875         1       3   

  Sex_ Embarked_ Age_  
0    1         3    1  
1    0         1    4  
2    1         3    2  
3    1         1    3  
4    0         1    3

In [43]:
Fare_group = [-1,8,15,30,100,200,550]
Fare_label = [1,2,3,4,5,6]
df['Fare_'] = pd.cut(df['Fare'],bins=Fare_group,labels=Fare_label)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   PassengerId  889 non-null    int64   
 1   Survived     889 non-null    int64   
 2   Pclass       889 non-null    int64   
 3   Sex          889 non-null    int64   
 4   Age          889 non-null    float64 
 5   SibSp        889 non-null    int64   
 6   Parch        889 non-null    int64   
 7   Fare         889 non-null    float64 
 8   Embarked     889 non-null    int64   
 9   Survived_    889 non-null    bool    
 10  Pclass_      889 non-null    category
 11  Sex_         889 non-null    category
 12  Embarked_    889 non-null    category
 13  Age_         889 non-null    category
 14  Fare_        889 non-null    category
dtypes: bool(1), category(5), float64(2), int64(7)
memory usage: 115.4 KB


In [44]:
df.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked  \
0            1         0       3    1  22.0      1      0   7.2500         1   
1            2         1       1    0  38.0      1      0  71.2833         2   
2            3         1       3    0  26.0      0      0   7.9250         1   
3            4         1       1    0  35.0      1      0  53.1000         1   
4            5         0       3    1  35.0      0      0   8.0500         1   

   Survived_ Pclass_ Sex_ Embarked_ Age_ Fare_  
0      False       3    1         1    1     1  
1       True       1    0         2    4     4  
2       True       3    0         1    2     1  
3       True       1    0         1    3     4  
4      False       3    1         1    3     2

In [45]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
Survived_      0
Pclass_        0
Sex_           0
Embarked_      0
Age_           0
Fare_          0
dtype: int64

In [190]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn import model_selection

In [176]:
#feature = ['Pclass_','Sex_','Age_','SibSp','Parch','Embarked','Fare_']
feature = ['Pclass_','Sex_','Age_','SibSp','Parch','Embarked','Fare_']
X = df[feature]
y = df['Survived']

In [177]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25)

In [192]:
kfold = model_selection.KFold(n_splits=5,random_state=1)

In [193]:
model = DecisionTreeClassifier()
cvs = model_selection.cross_val_score(model,X_train,y_train,cv=kfold)
#cvs = cross_val_score(model,X_train,y_train,cv=5)
cvs

array([0.81343284, 0.72932331, 0.78195489, 0.79699248, 0.83458647])

In [194]:
cvs.mean()

0.7912579957356077

In [195]:
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [196]:
y_pred = model.predict(X_test)

In [197]:
print(classification_report(y_test,y_pred,target_names=['Dead','Survived']))

              precision    recall  f1-score   support

        Dead       0.83      0.85      0.84       144
    Survived       0.72      0.67      0.69        79

    accuracy                           0.79       223
   macro avg       0.77      0.76      0.77       223
weighted avg       0.79      0.79      0.79       223



In [198]:
from sklearn.naive_bayes import GaussianNB

In [199]:
model2 = GaussianNB()
cvs2 = model_selection.cross_val_score(model2,X_train,y_train,cv=kfold)
#cvs2 = cross_val_score(model2,X_train,y_train,cv=5)
cvs2

array([0.7761194 , 0.7443609 , 0.79699248, 0.81203008, 0.7518797 ])

In [200]:
cvs2.mean()

0.7762765121759623

In [201]:
model2.fit(X_train,y_train)

GaussianNB()

In [202]:
y_pred2 = model2.predict(X_test)

In [203]:
print(classification_report(y_test,y_pred2,target_names=['Dead','Survived']))

              precision    recall  f1-score   support

        Dead       0.83      0.85      0.84       144
    Survived       0.72      0.67      0.69        79

    accuracy                           0.79       223
   macro avg       0.77      0.76      0.77       223
weighted avg       0.79      0.79      0.79       223



In [218]:
from sklearn.linear_model import LogisticRegression

In [219]:
model3 = LogisticRegression()
cvs3 = model_selection.cross_val_score(model3,X_train,y_train,cv=kfold)
cvs3

array([0.79850746, 0.77443609, 0.79699248, 0.79699248, 0.78195489])

In [226]:
cvs3.mean()

0.7897766805072383

In [240]:
model3.fit(X_train,y_train)

LogisticRegression()

In [241]:
y_pred3 = model3.predict(X_test)

In [242]:
print(classification_report(y_test,y_pred3,target_names=['Dead','Survived']))

              precision    recall  f1-score   support

        Dead       0.83      0.87      0.85       144
    Survived       0.74      0.67      0.70        79

    accuracy                           0.80       223
   macro avg       0.78      0.77      0.77       223
weighted avg       0.80      0.80      0.80       223



In [220]:
from sklearn.neural_network import MLPClassifier

In [246]:
model4 = MLPClassifier(hidden_layer_sizes=(200,),max_iter=100,alpha=1e-4,solver='sgd',verbose=10,tol=1e-5,random_state=1,learning_rate_init=0.01)
cvs4 = model_selection.cross_val_score(model4,X_train,y_train,cv=kfold)
cvs4

Iteration 1, loss = 0.75974856
Iteration 2, loss = 0.63705440
Iteration 3, loss = 0.63127210
Iteration 4, loss = 0.60744798
Iteration 5, loss = 0.57581694
Iteration 6, loss = 0.56304578
Iteration 7, loss = 0.55694580
Iteration 8, loss = 0.54627353
Iteration 9, loss = 0.53974704
Iteration 10, loss = 0.53410421
Iteration 11, loss = 0.52927174
Iteration 12, loss = 0.52326467
Iteration 13, loss = 0.51854306
Iteration 14, loss = 0.51340431
Iteration 15, loss = 0.50949169
Iteration 16, loss = 0.50494020
Iteration 17, loss = 0.50184786
Iteration 18, loss = 0.49768294
Iteration 19, loss = 0.49497605
Iteration 20, loss = 0.49112462
Iteration 21, loss = 0.48833533
Iteration 22, loss = 0.48607430
Iteration 23, loss = 0.48291966
Iteration 24, loss = 0.48088230
Iteration 25, loss = 0.47833878
Iteration 26, loss = 0.47619925
Iteration 27, loss = 0.47471478
Iteration 28, loss = 0.47226981
Iteration 29, loss = 0.47101127
Iteration 30, loss = 0.46880650
Iteration 31, loss = 0.46757369
Iteration 32, los

array([0.79104478, 0.76691729, 0.82706767, 0.78947368, 0.79699248])

In [247]:
cvs4.mean()

0.7942991807877904

In [248]:
model4.fit(X_train,y_train)

Iteration 1, loss = 0.74921704
Iteration 2, loss = 0.62124303
Iteration 3, loss = 0.61467561
Iteration 4, loss = 0.57557104
Iteration 5, loss = 0.56046772
Iteration 6, loss = 0.55021371
Iteration 7, loss = 0.54003708
Iteration 8, loss = 0.53376261
Iteration 9, loss = 0.52783143
Iteration 10, loss = 0.51929560
Iteration 11, loss = 0.51506811
Iteration 12, loss = 0.50857796
Iteration 13, loss = 0.50241751
Iteration 14, loss = 0.49836976
Iteration 15, loss = 0.49358068
Iteration 16, loss = 0.48920134
Iteration 17, loss = 0.48540449
Iteration 18, loss = 0.48280454
Iteration 19, loss = 0.47862206
Iteration 20, loss = 0.47624445
Iteration 21, loss = 0.47379217
Iteration 22, loss = 0.47191920
Iteration 23, loss = 0.46864457
Iteration 24, loss = 0.46815101
Iteration 25, loss = 0.46461837
Iteration 26, loss = 0.46213866
Iteration 27, loss = 0.46149607
Iteration 28, loss = 0.45979926
Iteration 29, loss = 0.45860162
Iteration 30, loss = 0.45793729
Iteration 31, loss = 0.45620091
Iteration 32, los

MLPClassifier(hidden_layer_sizes=(200,), learning_rate_init=0.01, max_iter=100,
              random_state=1, solver='sgd', tol=1e-05, verbose=10)

In [249]:
y_pred4 = model4.predict(X_test)

In [251]:
print(classification_report(y_test,y_pred4,target_names=['Dead','Survived']))

              precision    recall  f1-score   support

        Dead       0.83      0.90      0.86       144
    Survived       0.78      0.66      0.71        79

    accuracy                           0.81       223
   macro avg       0.80      0.78      0.79       223
weighted avg       0.81      0.81      0.81       223



In [252]:
df2.head()

PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked Pclass_  \
0          892       3    1  34.5      0      0   7.8292         3       3   
1          893       3    0  47.0      1      0   7.0000         1       3   
2          894       2    1  62.0      0      0   9.6875         3       2   
3          895       3    1  27.0      0      0   8.6625         1       3   
4          896       3    0  22.0      1      1  12.2875         1       3   

  Sex_ Embarked_ Age_  
0    1         3    1  
1    0         1    4  
2    1         3    2  
3    1         1    3  
4    0         1    3

In [254]:
Fare_group = [-1,8,15,30,100,200,550]
Fare_label = [1,2,3,4,5,6]
df2['Fare_'] = pd.cut(df2['Fare'],bins=Fare_group,labels=Fare_label)
df2.head()

PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked Pclass_  \
0          892       3    1  34.5      0      0   7.8292         3       3   
1          893       3    0  47.0      1      0   7.0000         1       3   
2          894       2    1  62.0      0      0   9.6875         3       2   
3          895       3    1  27.0      0      0   8.6625         1       3   
4          896       3    0  22.0      1      1  12.2875         1       3   

  Sex_ Embarked_ Age_ Fare_  
0    1         3    1     1  
1    0         1    4     1  
2    1         3    2     2  
3    1         1    3     2  
4    0         1    3     2

In [255]:
feature = ['Pclass_','Sex_','Age_','SibSp','Parch','Embarked','Fare_']
XX = df2[feature]

In [256]:
y_pred5 = model4.predict(XX)

In [257]:
y_pred5

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [260]:
NK_submission = pd.DataFrame({'PassengerId':df2['PassengerId'],'Survived':y_pred5})
NK_submission.to_csv('submission.csv',index=False)